[package]
name = "axum-app"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"

tokio = { version = "1.38", features = ["full"] }
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

